### PR TITLE
JSS style guide is added

### PR DESCRIPTION
**Pull request by codeShaurya**
- JSS style guide added
- Fixed typo in Typography

#88

### CODE REVIEW

**Comment by GrosSacASac** [comment]
I don't understand why this would solve #80

**Comment by codeShaurya** [comment]
Best practices for js

**Comment by GrosSacASac** [comment]
sorry if I was unclear, I don't want more examples **showing** what to do.

Instead I want more instructions that **tell** what to do.

**Comment by codeShaurya** [comment]
Can you make your statement more clear?

**Comment by codeShaurya** [comment]
@GrosSacASac, I have update the PR

**Pull request merged**
